import { FruitsRegex, FishSpeciesList, UserConfig } from './userconfig';

export const HegeConfig = {
  userNamesToFind: ['Hegedűs Tamás László'],
  blacklist: [
    'halfilé', 'halszelet', 'halrud', 'rákragu', 'koktélrák',
    'tonhal', 'szardínia',
    'garnél(a|á)', 'polip', 'kagyló', 'tenger gyümölcs', 'tengeri gyümölcs',
    'gomb(a|á)', 'csiperk(e|é)', 'vargány(a|á)',
    '(sertés|kacsa|liba|csirke|szárnyas).?máj',
    'zúz(a|á)',
    'ceruzabab', 'héjas zöldborsó',
    'budapest sertés', 'milánói',
  ].concat(FishSpeciesList),
  warnList: ['hal', 'rák', 'máj'],
  blacklistExceptions: ['[^a-z]dhal', 'kagylótészta', 'kultúrák', 'lepkeszegmag', 'shalott hagyma'],
  mehList: ['tarhonya', 'főzelék', 'zöldbab', 'csirkeszárny',
    'wok zöldség', 'fahéj', 'kávé',
    'mátrai saláta'],
  favList1: ['kijevi', 'brassói', 'lyoni', 'floridai', 'borzas',
    'szűz', 'chilis bab',
    '^(?!.*leves).*(tepsis|házi|falusi|tejföl).{0,5}(burgonya|burgonyá|krumpli)(?!püré)',
    'bors.{0,5}(mártás|szósz)',
    '(' + FruitsRegex + '|mézes|édes).*leves',
    'paradicsomleves',
    'tápiókapuding', 'gyümölcsrizs',
    'édesburgony(a|á)',
    'cheddar',
    'padlizsánkrém',
    '(mangó|ananász).{0,5}rétes',
  ],
  favList2: ['hidasi', 'dijoni', 'mátrai',
    '(grillezett|bacon).{0,10}(burgonya|burgonyá|krumpli)(?!püré)',
    'aszalt paradicsom',
    'palak', 'tikka masala', 'corma', 'korma',
    'tzatziki', 'tartár', 'majonéz',
    'hagym(a|á)',
    'rózsabors',
    'rétes',
    'burrito', 'quesadilla',
    'coleslaw', 'káposztasaláta',
  ],
  testingList: [],
} as const satisfies UserConfig;
